### ISSUE TITLE
maven central artifact

### ISSUE THREAD

**Issue by mrniko** [jnr/jnr-process#10]
Please publish it to the maven central repo

**Comment by whymarrh** [comment]
@headius or @enebo would you folks be interested in publishing this?

**Comment by headius** [comment]
Hey there, missed this issue originally. I can certainly push it in its current state, if that would help you.

**Comment by headius** [comment]
Version 0.1 has been released to maven central.

**Comment by whymarrh** [comment]
Thanks a bunch! I appreciate it.
